export const initialState = {
  tasks: [],
  parentTasks: [],
  childTasks: [],
  timeLogs: [],
  task: {
    title: '',
    project: '',
    deadline: new Date().toISOString().split('T')[0],
    description: '',
    priority: '',
    createdBy: '',
    asignee: [],
    stage: '',
    tag: '',
    parent_task: [],
    child_task: [],
    time_log_ids: [],
  },
  parent_task: {
    title: '',
    project: '',
    deadline: new Date().toISOString().split('T')[0],
    description: '',
    priority: '',
    createdBy: '',
    asignee: '',
    stage: '',
    tag: '',
  },
  child_task: {
    title: '',
    project: '',
    deadline: new Date().toISOString().split('T')[0],
    description: '',
    priority: '',
    createdBy: '',
    asignee: '',
    stage: '',
    tag: '',
  },
  time_log: {
    employee: '',
    houres: '',
    date: new Date().toISOString().split('T')[0],
    billable: false,
  },
  other: {
    isParentTask: false,
    isChildTask: false,
    form_mode: {},
  },
};
