export const initialState = {
  tasks: [],
  parentTasks: [],
  childTasks: [],
  task: {
    title: '',
    project_id: '',
    deadline: new Date(),
    description: '',
    priority: '',
    createdBy: '',
    asignee: '',
    stage: '',
    tag: '',
    parent_task: [],
    child_task: [],
  },
  parent_task: {
    title: '',
    project_id: '',
    deadline: new Date(),
    description: '',
    priority: '',
    createdBy: '',
    asignee: '',
    stage: '',
    tag: '',
  },
  child_task: {
    title: '',
    project_id: '',
    deadline: new Date(),
    description: '',
    priority: '',
    createdBy: '',
    asignee: '',
    stage: '',
    tag: '',
  },
  other: {
    isParentTask: false,
    isChildTask: false,
    form_mode: {},
  },
};
